#! /bin/bash

# set default multi-monitor screen configuration

SCREEN1="eDP-1"
SCREEN2="HDMI-1"

xrandr --query | grep "${SCREEN2} connected"
case $? in
  0) xrandr --output ${SCREEN1} --mode 1920x1080 --pos 1600x0 --rotate normal --output ${SCREEN2} --mode 1600x900 --pos 0x90 --rotate normal ;;
  *) xrandr --output ${SCREEN1} --mode 1920x1080 --rotate normal --output ${SCREEN2} --off --pos 1920x0 ;;
esac

